# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=20, verbose_name='\u4f5c\u8005')),
                ('title', models.CharField(default='', max_length=50, verbose_name='\u6807\u9898')),
                ('content', models.TextField(default='', verbose_name='\u5185\u5bb9')),
                ('comments', models.TextField(default='', max_length=500, verbose_name='\u8bc4\u8bba')),
                ('like_nums', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u4eba\u6570')),
                ('image', models.ImageField(default='', upload_to='posts/%Y/%m', verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
