# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170417_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='posts.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
