# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170417_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/%Y/%m', verbose_name='\u6587\u7ae0\u56fe\u7247'),
        ),
    ]
