# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 20:12
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_tag_click_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
