# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20170425_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
